shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

shop_project/payment/urls.py
from django.urls import path
from . import views, webhooks


app_name = "payment"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webhook, name="webhook"),
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("user/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("", include("main.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_project/payment/models.py
from django.db import models

# Create your models here.

shop_project/payment/views.py
from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.conf import settings
from orders.models import Order
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }
        for item in order.items.all():
            discounted_price = item.product.sell_price()
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(discounted_price * Decimal("100")),
                        "currency": "usd",
                        "product_data": {
                            "name": item.product.name,
                        },
                    },
                    "quantity": item.quantity,
                }
            )
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, "payment/process.html", locals())


def payment_completed(request):
    return render(request, "payment/completed.html")


def payment_canceled(request):
    return render(request, "payment/canceled.html")

shop_project/payment/templates/payment/canceled.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Отклонение оплаты{% endblock title %}

{% block content %}
    <div class="text-center mt-5">
        <h1>Оплата была отклонена</h1>
    </div>
{% endblock content %}

shop_project/payment/templates/payment/completed.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Оплата прошла успешно{% endblock title %}

{% block content %}
    <div class="text-center mt-5">
        <h1>Оплата прошла успешно</h1>
    </div>
{% endblock content %}

shop_project/payment/templates/payment/process.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Процесс оплаты{% endblock title %}

{% block content %}
    <div class="window">
        <h2 class="pay-title">
            Оплата
        </h2>
        <div class="pay-card d-flex">
            <div class="cart-cardsproc">
                {% for item in order.items.all %}
                    {% with product=item.product %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{% if product.image %}{{ product.image.url }} {% else %} {% static 'img/noimage.png' %}{% endif %}" class="card-img" alt="">
                        </div>
                        <div class="cart-card-info">
                            <div class="cart-card-name">
                                <p>{{ product.name }}</p>
                            </div>
                            <div class="cart-card-q">
                                <p>Количество: {{ item.quantity }}</p>
                            </div>
                        </div>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Удаление" class="remove-btn">
                            {% csrf_token %}
                        </form>
                        <div class="cart-card-price">
                            {% if product.discount %}
                                <div class="cart-price">
                                    <p class="line opac">{{ product.price }} ₽</p>
                                    <p class="cart-total-price-ots">{{ product.sell_price }} ₽</p>
                                </div>
                            {% else %}
                                <p class="cart-total-price">{{ product.price }} ₽</p>
                            {% endif %}
                        </div>
                    </div>
                    {% endwith %}
                {% endfor %}

                <form action="{% url "payment:process" %}" method="post" class="payform">
                    <input type="submit" value="Оплатить" class="paynow">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}