shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

shop_project/orders/urls.py
from django.urls import path
from . import views


app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("user/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("", include("main.urls", namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_project/orders/models.py
from django.db import models
from django.conf import settings
from main.models import Product
from users.models import User


class Order(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    stripe_id = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=["-created"])]

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_stripe_url(self):
        if self.stripe_id:
            return ""
        if "__test__" in settings.STRIPE_SECRET_KEY:
            path = "/test"
        else:
            path = "/"
        return f"https://dashboard.stripe.com{path}/payments/{self.stripe_id}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop_project/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "user",
            "first_name",
            "last_name",
            "email",
            "address",
            "postal_code",
            "city",
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        if self.request.user.is_authenticated:
            self.initial["first_name"] = self.request.user.first_name
            self.initial["last_name"] = self.request.user.last_name
            self.initial["email"] = self.request.user.email

    def save(self, commit=True):
        order = super().save(commit=False)
        order.user = self.request.user
        if commit:
            order.save()
        return order

shop_project/orders/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from cart.cart import Cart
from .models import OrderItem
from .forms import OrderCreateForm


def order_create(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.save()
            for item in cart:
                discounted_price = item["product"].sell_price()
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=discounted_price,
                    quantity=item["quantity"],
                )
            cart.clear()
            request.session["order_id"] = order.id
            return redirect(reverse("payment:process"))
    else:
        form = OrderCreateForm(request=request)
    return render(request, "order/create.html", {"cart": cart, "form": form})

shop_project/orders/templates/order/create.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Создание заказа{% endblock title %}

{% block content %}
    <div class="forcreate bg-white p-4 mb-4 mx-2">
        <div class="order-form-1 bg-white p-4 mb-4 mx-2">
            <h2 class="mb-2">Создание заказа</h2>
            <form action="" method="post" class="order-form">
                {% csrf_token %}
                <div class="col-md-12 mb-3">
                    <label for="id_first_name" class="form-label">Имя</label>
                    <input type="text" class="form-control form-styleprofile" id="id_first_name"
                    name="first_name" placeholder="Ваше имя" value="{{ form.first_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_last_name" class="form-label">Фамилия</label>
                    <input type="text" class="form-control form-styleprofile" id="id_last_name"
                    name="last_name" placeholder="Ваша фамилия" value="{{ form.last_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    <input type="text" class="form-control form-styleprofile" id="id_email"
                    name="email" placeholder="Ваш email" value="{{ form.email.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_address" class="form-label">Адрес</label>
                    <input type="text" class="form-control form-styleprofile" id="id_address"
                    name="address" placeholder="Ваш адрес" value="{{ form.address.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_postal_code" class="form-label">Почтовый индекс</label>
                    <input type="text" class="form-control form-styleprofile" id="id_postal_code"
                    name="postal_code" placeholder="Ваш почтовый индекс" value="{{ form.postal_code.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_city" class="form-label">Город</label>
                    <input type="text" class="form-control form-styleprofile" id="id_city"
                    name="city" placeholder="Ваш город" value="{{ form.city.value|default:'' }}" required>
                </div>
                <p><input type="submit" value="Сделать заказ"></p>
                {% csrf_token %}
            </form>
        </div>
        <div class="checkout">
            <h1>Проверка</h1>
            <div class="order-info">
                {% for item in cart %}
                    <li>
                        {{ item.quantity }} x {{ item.product.name }}
                        <p>{{ item.total_price }}</p>
                    </li>
                    <p>Итого: {{ cart.get_total_price }} ₽</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

shop_project/orders/templates/order/created.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Заказ создан{% endblock title %}

{% block content %}
    <h1 class="text-center mt-5">Ваш заказ был создан</h1>
{% endblock content %}